export const NIFTY_50_STOCKS = [
  { symbol: '^NSEI',         label: 'Nifty 50 Index' },
  { symbol: 'RELIANCE.NS',   label: 'Reliance Industries' },
  { symbol: 'TCS.NS',        label: 'Tata Consultancy Services' },
  { symbol: 'HDFCBANK.NS',   label: 'HDFC Bank' },
  { symbol: 'INFY.NS',       label: 'Infosys' },
  { symbol: 'ICICIBANK.NS',  label: 'ICICI Bank' },
  { symbol: 'HINDUNILVR.NS', label: 'Hindustan Unilever' },
  { symbol: 'ITC.NS',        label: 'ITC Limited' },
  { symbol: 'SBIN.NS',       label: 'State Bank of India' },
  { symbol: 'BHARTIARTL.NS', label: 'Bharti Airtel' },
  { symbol: 'KOTAKBANK.NS',  label: 'Kotak Mahindra Bank' },
  { symbol: 'LT.NS',         label: 'Larsen & Toubro' },
  { symbol: 'AXISBANK.NS',   label: 'Axis Bank' },
  { symbol: 'ASIANPAINT.NS', label: 'Asian Paints' },
  { symbol: 'MARUTI.NS',     label: 'Maruti Suzuki' },
  { symbol: 'HCLTECH.NS',    label: 'HCL Technologies' },
  { symbol: 'SUNPHARMA.NS',  label: 'Sun Pharma' },
  { symbol: 'TITAN.NS',      label: 'Titan Company' },
  { symbol: 'BAJFINANCE.NS', label: 'Bajaj Finance' },
  { symbol: 'WIPRO.NS',      label: 'Wipro' },
  { symbol: 'ULTRACEMCO.NS', label: 'UltraTech Cement' },
  { symbol: 'NESTLEIND.NS',  label: 'Nestle India' },
  { symbol: 'POWERGRID.NS',  label: 'Power Grid Corporation' },
  { symbol: 'NTPC.NS',       label: 'NTPC' },
  { symbol: 'ONGC.NS',       label: 'ONGC' },
  { symbol: 'TECHM.NS',      label: 'Tech Mahindra' },
  { symbol: 'JSWSTEEL.NS',   label: 'JSW Steel' },
  { symbol: 'TATASTEEL.NS',  label: 'Tata Steel' },
  { symbol: 'ADANIENT.NS',   label: 'Adani Enterprises' },
  { symbol: 'ADANIPORTS.NS', label: 'Adani Ports' },
  { symbol: 'COALINDIA.NS',  label: 'Coal India' },
  { symbol: 'DRREDDY.NS',    label: "Dr. Reddy's Labs" },
  { symbol: 'CIPLA.NS',      label: 'Cipla' },
  { symbol: 'BAJAJFINSV.NS', label: 'Bajaj Finserv' },
  { symbol: 'TATAMOTORS.NS', label: 'Tata Motors' },
  { symbol: 'BRITANNIA.NS',  label: 'Britannia Industries' },
  { symbol: 'APOLLOHOSP.NS', label: 'Apollo Hospitals' },
  { symbol: 'HEROMOTOCO.NS', label: 'Hero MotoCorp' },
  { symbol: 'HINDALCO.NS',   label: 'Hindalco Industries' },
  { symbol: 'EICHERMOT.NS',  label: 'Eicher Motors' },
  { symbol: 'GRASIM.NS',     label: 'Grasim Industries' },
  { symbol: 'DIVISLAB.NS',   label: "Divi's Laboratories" },
  { symbol: 'INDUSINDBK.NS', label: 'IndusInd Bank' },
  { symbol: 'TATACONSUM.NS', label: 'Tata Consumer Products' },
  { symbol: 'BAJAJ-AUTO.NS', label: 'Bajaj Auto' },
  { symbol: 'BPCL.NS',       label: 'BPCL' },
  { symbol: 'HDFCLIFE.NS',   label: 'HDFC Life Insurance' },
  { symbol: 'SBILIFE.NS',    label: 'SBI Life Insurance' },
  { symbol: 'UPL.NS',        label: 'UPL Limited' },
  { symbol: 'MM.NS',         label: 'Mahindra & Mahindra' },
];

export const INTERVALS = [
  { value: '1d',  label: 'Daily',   short: '1D' },
  { value: '1wk', label: 'Weekly',  short: '1W' },
  { value: '1mo', label: 'Monthly', short: '1M' },
  { value: '1y',  label: 'Yearly',  short: '1Y' },
];
